# Generated by Django 5.2 on 2025-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawabati_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
