# Generated by Django 5.2 on 2025-04-24 15:19

import bawabati_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bawabati_app', '0002_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='notes/', validators=[bawabati_app.models.validate_file_extension]),
        ),
    ]
